common:
  data_dir_root: /Dataset/IsoGD
  dataset_splits: /CodeDir/AcmW_Code/dataset_splits

  init_model: ../checkpoints/epoch22-M-valid_0.5888-test_0.6289.pth
#  init_model: ../checkpoints/epoch24-K-valid_0.5568-test_0.6085.pth


#-------basic parameter----------
  visname: AutoGesture_AUG_Iso
  num_classes: 249
  batch_size: 24
  testing_batch_size: 256
  num_workers: 4
  learning_rate: 0.01
  momentum: 0.9
  weight_decay: 0.00005
  init_epochs: 0
  max_epochs: 80
  print_freq: 10
  pretrain: False
#-------------end----------------

#-------additional parameter-----
  sample_duration: 32

  # AutoGesture_searched
  init_channels8: 48
  init_channels16: 32
  init_channels32: 16
  layers: 12
#-------------end----------------
